export const AppointmentData = [
  {
    FirstName: "John",
    LastName: "Doe",
    Mobile: "9876543210",
    Email: "john.doe@example.com",
    Age: 35,
    Height: 175,
    Weight: 70,
    Gender: "Male",
    Address: "123 Main St, New York, NY",
    AppointmentDate: "2025-03-13",
    Time: "10:30 AM",
    DoctorName: "Dr. Smith",
    Payment: "UPI",
  },
  {
    FirstName: "Jane",
    LastName: "Smith",
    Mobile: "8765432109",
    Email: "jane.smith@example.com",
    Age: 28,
    Height: 162,
    Weight: 55,
    Gender: "Female",
    Address: "456 Elm St, Los Angeles, CA",
    AppointmentDate: "2025-03-10",
    Time: "2:00 PM",
    DoctorName: "Dr. Adams",
    Payment: "Cash",
  },
  {
    FirstName: "Michael",
    LastName: "Brown",
    Mobile: "7654321098",
    Email: "michael.brown@example.com",
    Age: 45,
    Height: 180,
    Weight: 85,
    Gender: "Male",
    Address: "789 Oak St, Chicago, IL",
    AppointmentDate: "2025-02-28",
    Time: "11:45 AM",
    DoctorName: "Dr. Johnson",
    Payment: "UPI",
  },
  {
    FirstName: "Emily",
    LastName: "Clark",
    Mobile: "6543210987",
    Email: "emily.clark@example.com",
    Age: 32,
    Height: 168,
    Weight: 60,
    Gender: "Female",
    Address: "321 Pine St, Houston, TX",
    AppointmentDate: "2025-03-12",
    Time: "9:15 AM",
    DoctorName: "Dr. Williams",
    Payment: "Pending",
  },
  {
    FirstName: "Robert",
    LastName: "Miller",
    Mobile: "5432109876",
    Email: "robert.miller@example.com",
    Age: 50,
    Height: 178,
    Weight: 90,
    Gender: "Male",
    Address: "987 Birch St, Phoenix, AZ",
    AppointmentDate: "2025-02-25",
    Time: "3:30 PM",
    DoctorName: "Dr. Anderson",
    Payment: "Credit Card",
  },
  {
    FirstName: "Ghanshyam",
    LastName: "Tiwari",
    Mobile: "9876543210",
    Email: "shyam.tiwari@example.com",
    Age: 53,
    Height: 175,
    Weight: 70,
    Gender: "Male",
    Address: "123 Main St, New York, NY",
    AppointmentDate: "2025-03-13",
    Time: "10:40 AM",
    DoctorName: "Dr. Smith",
    Payment: "Pending",
  },
  {
    FirstName: "Anil",
    LastName: "Kapoor",
    Mobile: "8765432108",
    Email: "anil.kapoor@example.com",
    Age: 18,
    Height: 162,
    Weight: 50,
    Gender: "Female",
    Address: "456 Elm St, Los Angeles, CA",
    AppointmentDate: "2025-03-10",
    Time: "3:00 PM",
    DoctorName: "Dr. Adams",
    Payment: "UPI",
  },
  {
    FirstName: "Michael",
    LastName: "Brown",
    Mobile: "7654321098",
    Email: "michael.brown@example.com",
    Age: 45,
    Height: 180,
    Weight: 85,
    Gender: "Male",
    Address: "789 Oak St, Chicago, IL",
    AppointmentDate: "2025-02-28",
    Time: "11:45 AM",
    DoctorName: "Dr. Johnson",
    Payment: "Credit Card",
  },
  {
    FirstName: "Emily",
    LastName: "Clark",
    Mobile: "6543210987",
    Email: "emily.clark@example.com",
    Age: 32,
    Height: 168,
    Weight: 60,
    Gender: "Female",
    Address: "321 Pine St, Houston, TX",
    AppointmentDate: "2025-03-12",
    Time: "9:15 AM",
    DoctorName: "Dr. Williams",
    Payment: "UPI",
  },
  {
    FirstName: "Robert",
    LastName: "Miller",
    Mobile: "5432109876",
    Email: "robert.miller@example.com",
    Age: 50,
    Height: 178,
    Weight: 90,
    Gender: "Male",
    Address: "987 Birch St, Phoenix, AZ",
    AppointmentDate: "2025-02-25",
    Time: "3:30 PM",
    DoctorName: "Dr. Anderson",
    Payment: "Pending",
  },
];
