export const staffsData = [
    {
      Id: 1,
      FirstName: "Alok",
      LastName: "Sharma",
      Mobile: "9900887744",
      Email: "alok.Sharma@drap.com",
      Qualification: "MBBS, MD US",
      Specialization: "Pediatrician",
      Department: "Orthopedics",
    },
    {
      Id: 2,
      FirstName: "Sumedh",
      LastName: "Giri",
      Mobile: "8700887799",
      Email: "sumedh.giri@drap.com",
      Qualification: "MBBS, MD US",
      Specialization: "Gastroenterologist",
      Department: "Orthopedics",
    },
    {
      Id: 3,
      FirstName: "Priya",
      LastName: "Patel",
      Mobile: "9800998877",
      Email: "priya.patel@drap.com",
      Qualification: "MBBS, MS",
      Specialization: "Cardiologist",
      Department: "Cardiology",
    },
    {
      Id: 4,
      FirstName: "John",
      LastName: "Doe",
      Mobile: "9900112233",
      Email: "john.doe@drap.com",
      Qualification: "MBBS, MD Cardiology",
      Specialization: "Cardiologist",
      Department: "Cardiology",
    },
    {
      Id: 5,
      FirstName: "Rita",
      LastName: "Mehta",
      Mobile: "8500556677",
      Email: "rita.mehta@drap.com",
      Qualification: "MBBS, MD Surgery",
      Specialization: "General Surgeon",
      Department: "Surgery",
    },
    {
      Id: 6,
      FirstName: "Mohan",
      LastName: "Kumar",
      Mobile: "9988776655",
      Email: "mohan.kumar@drap.com",
      Qualification: "MBBS, MD Anesthesia",
      Specialization: "Anesthesiologist",
      Department: "Anesthesia",
    },
    {
      Id: 7,
      FirstName: "Anjali",
      LastName: "Singh",
      Mobile: "9200112233",
      Email: "anjali.singh@drap.com",
      Qualification: "MBBS, MD Pediatrics",
      Specialization: "Pediatrician",
      Department: "Pediatrics",
    },
    {
      Id: 8,
      FirstName: "Ravi",
      LastName: "Verma",
      Mobile: "9300223344",
      Email: "ravi.verma@drap.com",
      Qualification: "MBBS, MS Orthopedics",
      Specialization: "Orthopedist",
      Department: "Orthopedics",
    },
    {
      Id: 9,
      FirstName: "Sneha",
      LastName: "Rao",
      Mobile: "9600334455",
      Email: "sneha.rao@drap.com",
      Qualification: "MBBS, MD Dermatology",
      Specialization: "Dermatologist",
      Department: "Dermatology",
    },
    {
      Id: 10,
      FirstName: "Vikram",
      LastName: "Yadav",
      Mobile: "9000445566",
      Email: "vikram.yadav@drap.com",
      Qualification: "MBBS, MD ENT",
      Specialization: "ENT Specialist",
      Department: "ENT",
    },
  ];
  